CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL
);

ALTER TABLE users ADD COLUMN email VARCHAR(100) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN verification_token VARCHAR(32);
ALTER TABLE users ADD COLUMN reset_token VARCHAR(32);
ALTER TABLE users ADD COLUMN reset_token_expires DATETIME;